from micropython import const

CMD_SET_FREQ           = const(0x01)
CMD_START_SUBGHZ_SCAN  = const(0x02)
CMD_REPLAY_SUBGHZ      = const(0x03)
CMD_START_DEAUTH       = const(0x04)
CMD_BEACON_SPAM        = const(0x05)
CMD_NRF_HONEYPOT       = const(0x06)
CMD_BLE_SNIFF          = const(0x07)
CMD_STOP_ALL           = const(0x08)
CMD_SET_MODULATION     = const(0x09)
CMD_START_SCAN         = const(0x0A)
CMD_START_SNIFF        = const(0x0B)
CMD_REPLAY             = const(0x0C)
CMD_RAW_TX             = const(0x0D)
CMD_SET_POWER          = const(0x0E)
CMD_SPECTRUM_SWEEP     = const(0x0F)
CMD_RF_ON              = const(0x14)
CMD_RF_OFF             = const(0x15)
CMD_PREPARE_SHUTDOWN   = const(0x16)
CMD_QUERY_POWER_STATE  = const(0x17)
CMD_JAMMER             = const(0x40)
CMD_REBOOT             = const(0xFE)
CMD_SHUTDOWN           = const(0xFF)

TLV_KEEPALIVE          = const(0xFF)
TLV_SUBGHZ_PACKET      = const(0x10)
TLV_NRF_HID_EVENT      = const(0x11)
TLV_WIFI_FRAME         = const(0x12)
TLV_BLE_ADV            = const(0x13)
TLV_RSSI_REPORT        = const(0x20)
TLV_STATUS             = const(0x21)
TLV_LOG                = const(0xF0)
